experiment_id: full-eval-2model-224x1-20260226

tasks:
  - .tmp/abc_out/task_15dkatz_official_joke_api__filtered_joke_lookup
  - .tmp/abc_out/task_15dkatz_official_joke_api__metadata
  - .tmp/abc_out/task_15dkatz_official_joke_api__random_jokes
  - .tmp/abc_out/task_15dkatz_official_joke_api__root_and_health
  - .tmp/abc_out/task_1chz_realworld_java21_springboot3__article_comments
  - .tmp/abc_out/task_1chz_realworld_java21_springboot3__article_favorites
  - .tmp/abc_out/task_1chz_realworld_java21_springboot3__articles
  - .tmp/abc_out/task_1chz_realworld_java21_springboot3__profiles_relationships
  - .tmp/abc_out/task_1chz_realworld_java21_springboot3__tags
  - .tmp/abc_out/task_1chz_realworld_java21_springboot3__users_authentication
  - .tmp/abc_out/task_3pillarlabs_socialauth__contacts_and_sharing
  - .tmp/abc_out/task_3pillarlabs_socialauth__registration_and_account_linking
  - .tmp/abc_out/task_99designs_gqlgen__todo_graphql_api
  - .tmp/abc_out/task_active_elastic_job_active_elastic_job__health
  - .tmp/abc_out/task_active_elastic_job_active_elastic_job__job_dispatch
  - .tmp/abc_out/task_active_elastic_job_active_elastic_job__random_strings
  - .tmp/abc_out/task_adrianvlupu_c4_builder__static_documentation_delivery
  - .tmp/abc_out/task_adventurelookup_adventurelookup__adventure_search_api
  - .tmp/abc_out/task_adventurelookup_adventurelookup__autocomplete_similarity
  - .tmp/abc_out/task_aidotnet_opendeepwiki__authentication_self_service
  - .tmp/abc_out/task_aidotnet_opendeepwiki__configuration_files_integrations
  - .tmp/abc_out/task_aidotnet_opendeepwiki__localization_knowledge_delivery
  - .tmp/abc_out/task_air_go_rpc__health_and_diagnostics
  - .tmp/abc_out/task_air_go_rpc__metadata
  - .tmp/abc_out/task_air_go_rpc__utility
  - .tmp/abc_out/task_allanzhuo_yyblog__wechat_mini_program_content_apis
  - .tmp/abc_out/task_amatsuda_html5_validators__item_html5_validation_demos
  - .tmp/abc_out/task_amatsuda_html5_validators__people_html5_validation_demos
  - .tmp/abc_out/task_amoniacou_danthes__health_and_channels
  - .tmp/abc_out/task_amsgames_laravel_shop__administrative
  - .tmp/abc_out/task_amsgames_laravel_shop__catalog_and_cart
  - .tmp/abc_out/task_amsgames_laravel_shop__checkout_and_orders
  - .tmp/abc_out/task_amsgames_laravel_shop__configuration_and_gateways
  - .tmp/abc_out/task_amsgames_laravel_shop__health_and_documentation
  - .tmp/abc_out/task_angelsix_fasetto_word__authentication
  - .tmp/abc_out/task_angelsix_fasetto_word__contacts
  - .tmp/abc_out/task_angelsix_fasetto_word__user_profile
  - .tmp/abc_out/task_angelsix_fasetto_word__web_utilities
  - .tmp/abc_out/task_ankitpokhrel_tus_php__tus_upload_management
  - .tmp/abc_out/task_ankur_anand_simple_sso__sso_server
  - .tmp/abc_out/task_ardalis_cachedrepository__catalog_pages
  - .tmp/abc_out/task_ardalis_cleanarchitecture__contributors
  - .tmp/abc_out/task_ashirt_ops_ashirt_server__evidence
  - .tmp/abc_out/task_ashirt_ops_ashirt_server__health
  - .tmp/abc_out/task_ashirt_ops_ashirt_server__operations
  - .tmp/abc_out/task_ashirt_ops_ashirt_server__tags
  - .tmp/abc_out/task_assaf_rack_oauth2_server__oauth_authorization_flow
  - .tmp/abc_out/task_assaf_rack_oauth2_server__practice_demo_resources
  - .tmp/abc_out/task_attacomsian_code_examples__file_upload_apis
  - .tmp/abc_out/task_auth0_auth0_react__root_health
  - .tmp/abc_out/task_auth0_auth0_react__users
  - .tmp/abc_out/task_awakencn_almost_famous__login_service
  - .tmp/abc_out/task_aws_samples_serverless_test_samples__unicorn_reservation_apis
  - .tmp/abc_out/task_azat_co_expressworks__book_catalog
  - .tmp/abc_out/task_azat_co_expressworks__service_metadata
  - .tmp/abc_out/task_azat_co_expressworks__utility_operations
  - .tmp/abc_out/task_azure_apiops__helloworld_function_app
  - .tmp/abc_out/task_azure_apiops__logic_app_manual_trigger
  - .tmp/abc_out/task_azure_apiops__test_api
  - .tmp/abc_out/task_azure_azure_sdk_for_go__recording_sanitizer_mock_server
  - .tmp/abc_out/task_azure_dev_spaces__values_api
  - .tmp/abc_out/task_azure_samples_cosmos_db_design_patterns__document_versioning_demo
  - .tmp/abc_out/task_azure_samples_eshoponazure__webhook_client_utility_endpoints
  - .tmp/abc_out/task_benediktalkin_songtaggerforspotify__album_tagging
  - .tmp/abc_out/task_benediktalkin_songtaggerforspotify__connection
  - .tmp/abc_out/task_blazorstatic_blazorstatic__home
  - .tmp/abc_out/task_brandur_rocket_rides_atomic__rides
  - .tmp/abc_out/task_bretfisher_node_docker_good_defaults__documents
  - .tmp/abc_out/task_bretfisher_node_docker_good_defaults__root_and_health
  - .tmp/abc_out/task_capacitorset_box_js__analysis_artifacts
  - .tmp/abc_out/task_capacitorset_box_js__sample_lifecycle
  - .tmp/abc_out/task_capacitorset_box_js__server_controls
  - .tmp/abc_out/task_carteb_carte_blanche__component_metadata
  - .tmp/abc_out/task_carteb_carte_blanche__component_variations
  - .tmp/abc_out/task_cassiomolin_log_aggregation_spring_boot_elastic_stack__comments
  - .tmp/abc_out/task_cassiomolin_log_aggregation_spring_boot_elastic_stack__posts
  - .tmp/abc_out/task_clevergo_clevergo__health_and_greetings
  - .tmp/abc_out/task_clevergo_clevergo__user_directory
  - .tmp/abc_out/task_clevergo_clevergo__utility
  - .tmp/abc_out/task_cloudinary_cloudinarydotnet__gallery
  - .tmp/abc_out/task_cloudinary_cloudinarydotnet__upload
  - .tmp/abc_out/task_composer_packagist__downloads_metrics
  - .tmp/abc_out/task_composer_packagist__operations_health
  - .tmp/abc_out/task_composer_packagist__package_maintenance
  - .tmp/abc_out/task_composer_packagist__security_compliance
  - .tmp/abc_out/task_conclave_team_conclave__page_rendering
  - .tmp/abc_out/task_conclave_team_conclave__peer_signaling
  - .tmp/abc_out/task_cornflourblue_dotnet_6_crud_api__users
  - .tmp/abc_out/task_cornflourblue_dotnet_6_jwt_refresh_tokens_api__users
  - .tmp/abc_out/task_cretueusebiu_laravel_vue_spa__account_settings
  - .tmp/abc_out/task_cretueusebiu_laravel_vue_spa__email_verification
  - .tmp/abc_out/task_cretueusebiu_laravel_vue_spa__registration_and_recovery
  - .tmp/abc_out/task_cretueusebiu_laravel_vue_spa__session_and_authenticated_user
  - .tmp/abc_out/task_cretueusebiu_laravel_vue_spa__spa_delivery
  - .tmp/abc_out/task_crmne_ruby_llm__health
  - .tmp/abc_out/task_cucumber_cucumber_jvm__user_pages
  - .tmp/abc_out/task_dailycodebuffer_spring_mvc_tutorials__book_catalog
  - .tmp/abc_out/task_dailycodebuffer_spring_mvc_tutorials__employee_management
  - .tmp/abc_out/task_danielschuster_muc_potter_db__books_chapters
  - .tmp/abc_out/task_danielschuster_muc_potter_db__characters
  - .tmp/abc_out/task_danielschuster_muc_potter_db__graphql
  - .tmp/abc_out/task_danielschuster_muc_potter_db__movies
  - .tmp/abc_out/task_danielschuster_muc_potter_db__potions
  - .tmp/abc_out/task_danielschuster_muc_potter_db__spells
  - .tmp/abc_out/task_darkweak_souin__debug_profiling
  - .tmp/abc_out/task_daspinola_video_stream_sample__video_delivery
  - .tmp/abc_out/task_davila7_claude_code_templates__blog_content
  - .tmp/abc_out/task_devinsays_laravel_react_bootstrap__todo
  - .tmp/abc_out/task_devmentors_packit__packing_lists
  - .tmp/abc_out/task_dotnet_dotnet_monitor__diagnostics_collection
  - .tmp/abc_out/task_dotnet_dotnext__hyparview_gossip_peer
  - .tmp/abc_out/task_dtm_labs_client_csharp__tcc_samples
  - .tmp/abc_out/task_eduardoboucas_staticman__repository_onboarding
  - .tmp/abc_out/task_eduardoboucas_staticman__root
  - .tmp/abc_out/task_elmassimo_oj_serializers__albums
  - .tmp/abc_out/task_email_dashboard_email_dashboard__health
  - .tmp/abc_out/task_email_dashboard_email_dashboard__notifications
  - .tmp/abc_out/task_exoego_rspec_openapi__admin_extensions
  - .tmp/abc_out/task_exoego_rspec_openapi__images
  - .tmp/abc_out/task_exoego_rspec_openapi__mounted_apps
  - .tmp/abc_out/task_exoego_rspec_openapi__secret_structured_data
  - .tmp/abc_out/task_exoego_rspec_openapi__sites_pages
  - .tmp/abc_out/task_exoego_rspec_openapi__tables
  - .tmp/abc_out/task_external_secrets_kubernetes_external_secrets__metrics
  - .tmp/abc_out/task_filipedeschamps_video_maker__health
  - .tmp/abc_out/task_filipedeschamps_video_maker__oauth_support
  - .tmp/abc_out/task_flippercloud_flipper__actor_targeting
  - .tmp/abc_out/task_flippercloud_flipper__bulk_import
  - .tmp/abc_out/task_flippercloud_flipper__feature_reset
  - .tmp/abc_out/task_flycash_toy_web__static_assets
  - .tmp/abc_out/task_flycash_toy_web__utility_services
  - .tmp/abc_out/task_getmoneynote_moneynote_api__accounts_payees_currency
  - .tmp/abc_out/task_getmoneynote_moneynote_api__balance_flows_attachments_notes
  - .tmp/abc_out/task_getmoneynote_moneynote_api__categories_tags_relations
  - .tmp/abc_out/task_go_spatial_tegola__map_style
  - .tmp/abc_out/task_go_spatial_tegola__vector_tiles
  - .tmp/abc_out/task_hagopj13_node_express_boilerplate__authentication
  - .tmp/abc_out/task_hagopj13_node_express_boilerplate__users
  - .tmp/abc_out/task_haozhang95_python24__cart_apis
  - .tmp/abc_out/task_haozhang95_python24__core_pages
  - .tmp/abc_out/task_haozhang95_python24__order_apis
  - .tmp/abc_out/task_havunen_systemtextjsonpatch__weather_forecasts
  - .tmp/abc_out/task_hgraca_explicit_architecture_php__admin_auth
  - .tmp/abc_out/task_hgraca_explicit_architecture_php__homepage
  - .tmp/abc_out/task_houarizegai_tutorials__student_management
  - .tmp/abc_out/task_hyperstack_org_hyperstack__realtime_transport_channel_management
  - .tmp/abc_out/task_intaro_pinboard__root_dashboard
  - .tmp/abc_out/task_intaro_pinboard__server_metrics_tables
  - .tmp/abc_out/task_intaro_pinboard__server_overview
  - .tmp/abc_out/task_isaiah_jubilee__sinatra_basic_sample
  - .tmp/abc_out/task_izghua_go_blog__console_authentication
  - .tmp/abc_out/task_jagenjo_litegraph_js__static_asset_delivery
  - .tmp/abc_out/task_jamesmh_coravel__demo_cache
  - .tmp/abc_out/task_jamhall_s3rver__bucket_operations
  - .tmp/abc_out/task_jamhall_s3rver__service_root
  - .tmp/abc_out/task_jeffreyway_council__json_api
  - .tmp/abc_out/task_jeffreyway_council__profiles_and_notifications
  - .tmp/abc_out/task_jellyfangs_messenger_bot_tutorial__facebook_webhook
  - .tmp/abc_out/task_jellyfangs_messenger_bot_tutorial__root
  - .tmp/abc_out/task_joakimk_testbot__runners
  - .tmp/abc_out/task_kawhii_sso__oauth_token_proxy
  - .tmp/abc_out/task_kawhii_sso__oauth_user_proxy
  - .tmp/abc_out/task_kawhii_sso__service_health
  - .tmp/abc_out/task_khellang_middleware__problemdetails_demo_endpoints
  - .tmp/abc_out/task_kogosoftwarellc_open_api__api_docs
  - .tmp/abc_out/task_konbai_q_ruoyi_flowable_plus__user_profile_management
  - .tmp/abc_out/task_laqul_laqul__graphql_api
  - .tmp/abc_out/task_laqul_laqul__registration_recovery
  - .tmp/abc_out/task_laqul_laqul__token_social_login
  - .tmp/abc_out/task_linezero_gitserver__repository_browsing
  - .tmp/abc_out/task_liuxx_u_bird_java__sso_ticket_server
  - .tmp/abc_out/task_liyupi_father__emoji_management
  - .tmp/abc_out/task_maccman_go__link_management
  - .tmp/abc_out/task_microsoft_powerbi_developer_samples__embedding_workflow
  - .tmp/abc_out/task_microsoftgraph_aspnetcore_webhooks_sample__notification_listener
  - .tmp/abc_out/task_mobomo_green_onion__sample_screenshot_pages
  - .tmp/abc_out/task_nelmio_nelmiojsloggerbundle__javascript_error_logging
  - .tmp/abc_out/task_neozhu_cleanaspire__file_management
  - .tmp/abc_out/task_neozhu_cleanaspire__products
  - .tmp/abc_out/task_neozhu_cleanaspire__tenants
  - .tmp/abc_out/task_nhost_hasura_auth__authentication
  - .tmp/abc_out/task_nonacosa_new_bee__github_oauth
  - .tmp/abc_out/task_ntxinh_aspnetcore_ddd__account_v2
  - .tmp/abc_out/task_paiden_nett__configuration_inspection
  - .tmp/abc_out/task_ploi_roadmap__activity_widget
  - .tmp/abc_out/task_ploi_roadmap__widget_embeds
  - .tmp/abc_out/task_pomzwj_database_export__schema_export
  - .tmp/abc_out/task_protonemedia_laravel_splade__country_data_api
  - .tmp/abc_out/task_rageagainstthepixel_openai_dotnet__health
  - .tmp/abc_out/task_rageagainstthepixel_openai_dotnet__openai_proxy
  - .tmp/abc_out/task_reactjs_react_net__tutorial_comments_reactnet_vanilla
  - .tmp/abc_out/task_restsend_rustpbx__ami_management_api
  - .tmp/abc_out/task_restsend_rustpbx__nat_traversal_ice
  - .tmp/abc_out/task_restsend_rustpbx__root_health
  - .tmp/abc_out/task_rubygems_rubygems_org__compact_index
  - .tmp/abc_out/task_rubygems_rubygems_org__statistics_activity_dependency_feeds_api_v1
  - .tmp/abc_out/task_samanazadi1996_sam_cleanarchitecture__account
  - .tmp/abc_out/task_sharpenrocks_sharpen__values
  - .tmp/abc_out/task_simplyvinay_vue_expenses__statistics
  - .tmp/abc_out/task_ssssssss_team_magic_api__data_source_utilities
  - .tmp/abc_out/task_stidsborg_cleipnir_net__sample_ordercontroller_samples_cleipnir_flows_sample_aspnet
  - .tmp/abc_out/task_stripe_archive_timberlake__job_control_and_streaming
  - .tmp/abc_out/task_stripe_samples_accept_a_payment__client_bootstrap
  - .tmp/abc_out/task_stripe_samples_accept_a_payment__payment_lifecycle
  - .tmp/abc_out/task_swaggo_swag__accounts
  - .tmp/abc_out/task_threedr3am_learnjavabug__shiro_auth_bypass_demo
  - .tmp/abc_out/task_thunderdev1_reactjs_ts_identityserver__sample_values_api
  - .tmp/abc_out/task_tongjilibo_bert4torch__openai_compatible_chat_service
  - .tmp/abc_out/task_totodore_socketioxide__http_routes
  - .tmp/abc_out/task_tsileo_blobstash__apps_gateway
  - .tmp/abc_out/task_tsileo_blobstash__document_store
  - .tmp/abc_out/task_tsileo_blobstash__file_tree
  - .tmp/abc_out/task_tsileo_blobstash__stash_management
  - .tmp/abc_out/task_tsileo_blobstash__sync
  - .tmp/abc_out/task_tsileo_blobstash__system
  - .tmp/abc_out/task_ttulka_ddd_example_ecommerce__portal_web
  - .tmp/abc_out/task_ttulka_ddd_example_ecommerce__shipping_delivery_api
  - .tmp/abc_out/task_unosquare_passcore__password_configuration
  - .tmp/abc_out/task_v5tech_elasticsearch_jest_example__article_search_ui
  - .tmp/abc_out/task_wangningkai_olaindex__image_hosting_public_api
  - .tmp/abc_out/task_welldone_software_why_did_you_render__demo_dev_server
  - .tmp/abc_out/task_withsalt_bilibililivetools__live_room_settings
  - .tmp/abc_out/task_zhongjinggz_geekdemo__organization_management
  - .tmp/abc_out/task_zzzzbw_fame__comments_media_settings

lineups:
  - name: kimi-k2.5
    planner_model: moonshotai/kimi-k2.5
    coder_a_model: moonshotai/kimi-k2.5
    coder_b_model: moonshotai/kimi-k2.5
    role_command: scripts/dspy_role_driver.py
    role_env:
      OPENROUTER_API_KEY_ENV: OPEN_ROUTER_API_KEY
      OPENROUTER_APP_TITLE: loopbench-team
      OPENROUTER_HTTP_REFERER: https://localhost/loopbench
      OPENROUTER_TEMPERATURE: "0.2"
      OPENROUTER_MAX_TOKENS: "16384"
      OPENROUTER_HTTP_TIMEOUT_SEC: "90"
      OPENROUTER_HTTP_RETRIES: "4"


  - name: deepseek-v3.2
    planner_model: deepseek/deepseek-v3.2
    coder_a_model: deepseek/deepseek-v3.2
    coder_b_model: deepseek/deepseek-v3.2
    role_command: scripts/dspy_role_driver.py
    role_env:
      OPENROUTER_API_KEY_ENV: OPEN_ROUTER_API_KEY
      OPENROUTER_APP_TITLE: loopbench-team
      OPENROUTER_HTTP_REFERER: https://localhost/loopbench
      OPENROUTER_TEMPERATURE: "0.2"
      OPENROUTER_MAX_TOKENS: "16384"
      OPENROUTER_HTTP_TIMEOUT_SEC: "90"
      OPENROUTER_HTTP_RETRIES: "4"
      OPENROUTER_REASONING_ENABLED: "false"


rollouts_per_task: 1
max_parallel_rollouts: 30
available_agent_sandboxes: 100
runtime_config: configs/runtime.e2b.openrouter.longrun.yaml
